### ISSUE TITLE
Keran West 3's shoe is off the footplate.

### ISSUE THREAD

**Issue by ghiret** [13enedict/CCRC#30] opened 2015-12-07 22:36 UTC
During the novice outing last yesterday, the right shoe of Kieran West's 3's seat(probably too many apostrophes...) came off.

**Comment by 13enedict** [comment] 2015-12-07 22:37
This is a duplicate of #29 but I pat you on the back for reporting it 👍🏻

**Closed by 13enedict** 2015-12-07 22:37 UTC
Labels: duplicate
