### ISSUE TITLE
Connector and electrical wires malfunction on Doreen

### ISSUE THREAD

**Issue by adrianalexa** [13enedict/CCRC#317] opened 2018-12-05 23:11 UTC
### Boat name or ID
Doreen

### Problem description
The connector for the cox box and the wires are old and malfunction. There are some small connectors  and the wires broke. We had to improvise again to make the cox box work. All that area - connectors and wires require a though review and most likely replace.
 
### Seat number(s) affected
cox

**Comment by NSinclair94** [comment] 2019-02-05 12:50
This is being looked at this weekend. Closing as it is a duplicate of another issue.

**Closed as completed by NSinclair94** 2019-02-05 12:50 UTC
